[custom.all.freer]
type   = "local"
path   = "."
ipkg   = "freer.ipkg"

[custom.all.tailrec]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-tailrec"
commit = "latest:main"
ipkg   = "tailrec.ipkg"
